### ISSUE TITLE
Sistema de Treinamento em Tecnologia

### ISSUE THREAD

**Issue by echovenancio** [grepvenancio/HackathonDSM3#4]
# Sistema de Treinamento em Tecnologia

Imagine que você está desenvolvendo um sistema para gerenciar o treinamento de 
programadores em uma empresa. 

## Crie uma classe Treinamento com os seguintes  atributos:
+ id (int): identificador único do treinamento.
+ nomeInstrutor (String): nome do instrutor do treinamento.
+ linguagemEnsinada (String): linguagem de programação ensinada no treinamento.
+ alunos (ArrayList<Aluno>): lista de alunos inscritos no treinamento, onde Aluno 
possui os atributos nome (String) e notaFinal (double).

## Adicione métodos para aplicar regras de negócios, como:
+ verificarDisponibilidade(): método que verifica a disponibilidade do instrutor para o 
treinamento.
+ definirCargaHoraria(int horas): método que define a carga horária do treinamento.
+ verificarUltimoTreinamento(Aluno aluno): método que verifica se um programador 
pode fazer o treinamento, considerando o limite de 80 horas a cada 2 meses.
+ calcularMediaAlunos(): método que calcula a média das notas finais dos alunos 
após o treinamento.

Utilize o conceito de polimorfismo para criar subclasses específicas para treinamentos 
presenciais e online. Cada uma dessas subclasses deve ter métodos específicos para o 
tipo de treinamento.

**Crie a classe TreinamentoPresencial com um atributo adicional local (String) e a 
classe TreinamentoOnline com um atributo adicional linkAcesso (String).**

**Comment by echovenancio** [comment]
# Ações necessárias para mudar para esse branch.

```
git fetch origin
git checkout tecnologia

-- Commitar o código
git add _arquivo_
git commit -am "mensagem"
git push origin tecnologia
```

**Comment by echovenancio** [comment]
@Zzymandias tem o macete pra fazer esse?

**Comment by Zzymandias** [comment]
> @Zzymandias tem o macete pra fazer esse?

Vou tentar, to chegando em casa já

**Comment by echovenancio** [comment]
> > @Zzymandias tem o macete pra fazer esse?
> 
> Vou tentar, to chegando em casa já

ok
